#!/bin/bash

# Function to perform linear search
linear_search() {
    target=$1
    shift
    arr=("$@")

    found=0

    for ((i=0; i<${#arr[@]}; i++))
    do
        if [ ${arr[$i]} -eq $target ]
        then
            echo "Element $target found at index $i"
            found=1
            break
        fi
    done

    if [ $found -eq 0 ]
    then
        echo "Element $target not found in the array"
    fi
}

# Usage example
numbers=(5 9 3 7 2 1)
search_number=7

linear_search $search_number "${numbers[@]}"
