#!/bin/bash

echo "Enter the value of x: "
read x

echo "Enter the number of terms: "
read num_terms

result=1
sign=-1
term=$x
factorial=1

for (( i=1; i<=num_terms; i++ ))
do
    term=$(bc -l <<< "$term * $x")
    factorial=$((factorial * i))
    term=$(bc -l <<< "$term / $factorial")
    term=$(bc -l <<< "$term * $sign")
    result=$(bc -l <<< "$result + $term")
    sign=$((sign * -1))
done

echo "e^(-1) = $result"
