#!/bin/bash

echo "Enter the first number: "
read num1

echo "Enter the second number: "
read num2

if (( num1 > num2 )); then
    echo "The first number ($num1) is bigger."
elif (( num1 < num2 )); then
    echo "The second number ($num2) is bigger."
else
    echo "Both numbers are equal."
fi
