#!/bin/bash

echo "Enter an integer number: "
read number

# Convert the number to a string
number_str="$number"

sum=0
for (( i=0; i<${#number_str}; i++ ))
do
    digit="${number_str:i:1}"
    sum=$((sum + digit))
done

echo "Sum of the digits: $sum"
